---
version: '3.8'

services:
  postgresql-db:
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=passwd123
      - POSTGRES_DB=db
